#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const mode = process.argv[2] || 'production';
const customPort = process.argv[3] || '5173';
const timestamp = Date.now();

// Detect local development server URL
function getDevServerUrl() {
    const port = customPort;
    
    // Try to detect if we're in a Laravel Valet/Herd environment
    const cwd = process.cwd();
    const projectName = path.basename(path.dirname(cwd));
    
    // Common local development patterns
    const possibleUrls = [
        `http://localhost:${port}`,
        `http://127.0.0.1:${port}`,
    ];
    
    return possibleUrls[0]; // Default to localhost for now
}

const devServerUrl = getDevServerUrl();

const envConfig = `<?php
/**
 * FC Autoposter Environment Configuration
 * This file is auto-generated by npm scripts
 * DO NOT EDIT MANUALLY
 * Generated at: ${new Date().toISOString()}
 */

// This file is overwritten by npm scripts
return [
    'mode' => '${mode}',
    'dev_server' => '${devServerUrl}',
    'timestamp' => ${timestamp}
];`;

const envConfigPath = path.join(__dirname, '..', 'env-config.php');

try {
    fs.writeFileSync(envConfigPath, envConfig);
    console.log(`✅ Environment mode set to: ${mode}`);
    console.log(`📁 Config written to: ${devServerUrl}`);
} catch (error) {
    console.error('❌ Error writing environment config:', error);
    process.exit(1);
}