<template>
  <div class="space-y-6">
    <!-- Dashboard Header -->
    <div class="border-b border-border pb-4">
      <h1 class="text-2xl font-bold text-foreground">Dashboard</h1>
      <p class="text-muted-foreground">Overview of your Fluent Community AI-powered post automation</p>
    </div>

    <!-- Stats Grid -->
    <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
      <Card v-for="stat in stats" :key="stat.title" class="p-6">
        <div class="flex items-center">
          <div class="flex-shrink-0">
            <div class="w-8 h-8 bg-primary/10 rounded-md flex items-center justify-center">
              <Icon :name="stat.icon" class="h-4 w-4 text-primary" />
            </div>
          </div>
          <div class="ml-4">
            <p class="text-sm font-medium text-muted-foreground">{{ stat.title }}</p>
            <p class="text-2xl font-semibold text-foreground">{{ stat.value }}</p>
          </div>
        </div>
      </Card>
    </div>

    <!-- Recent Posts and Quick Actions -->
    <div class="grid gap-6 lg:grid-cols-3">
      <!-- Recent Posts -->
      <div class="lg:col-span-2">
        <Card>
          <CardHeader>
            <CardTitle>Latest AI-Generated Posts</CardTitle>
            <CardDescription>Recent posts generated by AI integrations for Fluent Community</CardDescription>
          </CardHeader>
          <CardContent>
            <div v-if="recentPosts.length === 0" class="text-center py-8">
              <Icon name="fileText" class="h-12 w-12 text-muted-foreground mx-auto mb-4" />
              <p class="text-muted-foreground">No community posts yet</p>
              <p class="text-sm text-muted-foreground/70">Set up AI integrations to start generating community content</p>
            </div>
            <div v-else class="space-y-4">
              <div v-for="post in recentPosts" :key="post.id" 
                   class="flex items-center justify-between p-4 border rounded-lg hover:bg-muted/50">
                <div class="flex items-center space-x-4">
                  <Icon :name="getAiIcon(post.aiProvider)" class="h-5 w-5 text-muted-foreground" />
                  <div>
                    <p class="font-medium">{{ post.title }}</p>
                    <p class="text-sm text-muted-foreground">{{ post.aiProvider }} • {{ post.scheduledFor }}</p>
                  </div>
                </div>
                <div class="flex items-center space-x-2">
                  <Badge :variant="getStatusVariant(post.status)">
                    {{ post.status }}
                  </Badge>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      <!-- Quick Actions -->
      <div class="space-y-6">
        <Card>
          <CardHeader>
            <CardTitle>Quick Actions</CardTitle>
          </CardHeader>
          <CardContent class="space-y-3">
            <Button class="w-full justify-start" @click="createPost">
              <Icon name="plus" class="mr-2 h-4 w-4" />
              Generate New Post
            </Button>
            <Button variant="outline" class="w-full justify-start" @click="viewSchedule">
              <Icon name="calendar" class="mr-2 h-4 w-4" />
              View Schedule
            </Button>
            <Button variant="outline" class="w-full justify-start" @click="manageAiIntegrations">
              <Icon name="brain" class="mr-2 h-4 w-4" />
              AI Integrations
            </Button>
          </CardContent>
        </Card>

        <!-- AI Integrations Status -->
        <Card>
          <CardHeader>
            <CardTitle>AI Integrations Status</CardTitle>
          </CardHeader>
          <CardContent>
            <div class="space-y-3">
              <div v-for="integration in aiIntegrations" :key="integration.name"
                   class="flex items-center justify-between">
                <div class="flex items-center space-x-3">
                  <Icon :name="getAiIcon(integration.name)" class="h-4 w-4" />
                  <span class="text-sm">{{ integration.name }}</span>
                </div>
                <Badge :variant="integration.isActive ? 'default' : 'secondary'">
                  {{ integration.isActive ? 'Active' : 'Inactive' }}
                </Badge>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { Card, CardHeader, CardTitle, CardDescription, CardContent, Button, Badge, Icon } from '@/components/ui'

// Sample data
const stats = ref([
  { title: 'Total Scheduled Posts', value: '127', icon: 'schedule' },
  { title: 'Posts Publishing Today', value: '4', icon: 'clock' },
  { title: 'AI Generations Failed', value: '18', icon: 'alertTriangle' },
  { title: 'Successfully Published', value: '250', icon: 'checkCircle' }
])

const recentPosts = ref([
  {
    id: 1,
    title: 'Community Discussion: Best WordPress Practices',
    aiProvider: 'OpenAI GPT-4',
    status: 'Published',
    scheduledFor: '2 hours ago'
  },
  {
    id: 2,
    title: 'Weekly Community Highlights and Updates',
    aiProvider: 'Claude AI',
    status: 'Scheduled',
    scheduledFor: 'Tomorrow at 9:00 AM'
  },
  {
    id: 3,
    title: 'New Feature Tutorial: Community Groups',
    aiProvider: 'Gemini',
    status: 'Draft',
    scheduledFor: 'Not scheduled'
  }
])

const aiIntegrations = ref([
  { name: 'OpenAI GPT-4', isActive: true },
  { name: 'Claude AI', isActive: true },
  { name: 'Gemini', isActive: false },
  { name: 'Perplexity AI', isActive: false },
  { name: 'Mistral AI', isActive: false },
])

// Methods
const getAiIcon = (aiProvider) => {
  const icons = {
    'OpenAI GPT-4': 'brain',
    'Claude AI': 'brain',
    'Gemini': 'sparkles',
    'Perplexity AI': 'search',
    'Mistral AI': 'zap'
  }
  return icons[aiProvider] || 'cpu'
}

const getStatusVariant = (status) => {
  const variants = {
    'Published': 'default',
    'Scheduled': 'secondary',
    'Draft': 'outline',
    'Failed': 'destructive'
  }
  return variants[status] || 'outline'
}

const createPost = () => {
  console.log('Create post clicked')
}

const viewSchedule = () => {
  console.log('View schedule clicked')
}

const manageAiIntegrations = () => {
  console.log('Manage AI integrations clicked')
}
</script>