<template>
  <div class="space-y-6">
    <div class="flex justify-between items-center border-b border-border pb-4">
      <div>
        <h1 class="text-2xl font-bold text-foreground">Generated Posts</h1>
        <p class="text-muted-foreground">View and manage posts generated by agents</p>
      </div>
    </div>

    <Card class="p-6">
      <div v-if="loading" class="flex justify-center py-8">
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
      </div>

      <div v-else-if="error" class="bg-destructive/10 text-destructive p-4 rounded-md mb-4">
        {{ error }}
      </div>

      <div v-else>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>ID</TableHead>
              <TableHead>Title</TableHead>
              <TableHead>Agent</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Created At</TableHead>
              <TableHead class="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow v-for="post in posts" :key="post.id">
              <TableCell>#{{ post.id }}</TableCell>
              <TableCell class="font-medium">
                <a :href="`/wp-admin/post.php?post=${post.fcom_post_id}&action=edit`" target="_blank" class="hover:underline text-primary">
                  {{ post.post_title || '(No Title)' }}
                </a>
              </TableCell>
              <TableCell>
                <Badge variant="outline">{{ post.agent_name || 'Unknown' }}</Badge>
              </TableCell>
              <TableCell>
                <Badge :variant="getStatusVariant(post.post_status)">
                  {{ post.post_status }}
                </Badge>
              </TableCell>
              <TableCell>{{ formatDate(post.created_at) }}</TableCell>
              <TableCell class="text-right">
                <Button variant="ghost" size="sm" @click="deletePost(post.id)" class="text-destructive hover:text-destructive">
                  <TrashIcon class="w-4 h-4" />
                </Button>
              </TableCell>
            </TableRow>
            <TableRow v-if="posts.length === 0">
              <TableCell colspan="6" class="text-center py-8 text-muted-foreground">
                No posts found.
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>

        <!-- Pagination -->
        <div v-if="totalPages > 1" class="flex justify-center mt-4 space-x-2">
          <Button 
            variant="outline" 
            size="sm" 
            :disabled="currentPage === 1"
            @click="changePage(currentPage - 1)"
          >
            Previous
          </Button>
          <span class="flex items-center px-2 text-sm text-muted-foreground">
            Page {{ currentPage }} of {{ totalPages }}
          </span>
          <Button 
            variant="outline" 
            size="sm" 
            :disabled="currentPage === totalPages"
            @click="changePage(currentPage + 1)"
          >
            Next
          </Button>
        </div>
      </div>
    </Card>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { 
  Card, 
  Button, 
  Table, 
  TableHeader, 
  TableBody, 
  TableRow, 
  TableHead, 
  TableCell,
  Badge
} from '@/components/ui'
import { TrashIcon } from 'lucide-vue-next'
import { api } from '@/lib/api'

// State
const posts = ref([])
const loading = ref(true)
const error = ref(null)
const currentPage = ref(1)
const totalPages = ref(1)

// Methods
const fetchPosts = async (page = 1) => {
  loading.value = true
  error.value = null
  try {
    const response = await api.posts.getAll({ page, per_page: 10 })
    console.log('Posts API Response:', response)
    if (response.success) {
      posts.value = response.data.data
      currentPage.value = response.data.meta.current_page
      totalPages.value = response.data.meta.last_page
    } else {
      error.value = response.message || 'Failed to load posts'
    }
  } catch (err) {
    error.value = err.message || 'An error occurred'
  } finally {
    loading.value = false
  }
}

const changePage = (page) => {
  if (page >= 1 && page <= totalPages.value) {
    fetchPosts(page)
  }
}

const deletePost = async (id) => {
  if (!confirm('Are you sure you want to delete this post? This will also delete the WordPress post.')) return

  try {
    const response = await api.posts.delete(id)
    if (response.success) {
      fetchPosts(currentPage.value)
    } else {
      alert(response.message || 'Failed to delete')
    }
  } catch (err) {
    alert(err.message || 'An error occurred')
  }
}

const getStatusVariant = (status) => {
  switch (status) {
    case 'publish': return 'success'
    case 'draft': return 'secondary'
    case 'pending': return 'warning'
    case 'trash': return 'destructive'
    default: return 'outline'
  }
}

const formatDate = (dateString) => {
  if (!dateString) return '-'
  return new Date(dateString).toLocaleString()
}

// Lifecycle
onMounted(() => {
  fetchPosts()
})
</script>
